"""Packager v0 for image folders -> ADP (files mode, ADR-0003 M6 groundwork).

Input layout: `folder/<class>/<image>` (labeled) or `folder/<image>`
(unlabeled). Output: raw/ byte-exact copies, processed/{split}.jsonl sample
listings, manifest with mode="files", labels enumerated, seeded hash split
(same rule as tabular packages).
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from atom.data.packager import SPLIT_RATIOS, SPLIT_SEED, _hash_split, _sha256_file

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".gif", ".tiff", ".webp"}


def pack_images(folder: str | Path, out_dir: str | Path, name: str | None = None) -> Path:
    folder = Path(folder)
    name = name or folder.name
    root = Path(out_dir) / name
    for sub in ("raw", "processed", "splits"):
        (root / sub).mkdir(parents=True, exist_ok=True)

    samples = []  # (relpath, label)
    for f in sorted(folder.rglob("*")):
        if f.is_file() and f.suffix.lower() in IMAGE_EXTENSIONS:
            rel = f.relative_to(folder)
            label = rel.parts[0] if len(rel.parts) > 1 else None
            samples.append((rel, label))
    if not samples:
        raise ValueError(f"no image files found under {folder}")

    checksums, files, label_counts = {}, [], {}
    buckets = {s: [] for s in SPLIT_RATIOS}
    for rel, label in samples:
        dest = root / "raw" / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(folder / rel, dest)
        digest = _sha256_file(dest)
        checksums[f"raw/{rel}"] = digest
        files.append({"name": str(rel), "path": f"raw/{rel}",
                      "size_bytes": dest.stat().st_size, "sha256": digest,
                      "detected_type": rel.suffix.lstrip(".").lower(), "role": "data"})
        if label:
            label_counts[label] = label_counts.get(label, 0) + 1
        buckets[_hash_split(str(rel), SPLIT_RATIOS)].append(
            {"id": str(rel), "path": f"raw/{rel}", "label": label,
             "size_bytes": dest.stat().st_size})

    counts = {}
    for split, rows in buckets.items():
        dest = root / "processed" / f"{split}.jsonl"
        dest.write_text("".join(json.dumps(r) + "\n" for r in rows))
        checksums[f"processed/{split}.jsonl"] = _sha256_file(dest)
        counts[split] = len(rows)

    split_doc = {"version": "split_v1", "method": "hash", "seed": SPLIT_SEED,
                 "ratios": SPLIT_RATIOS, "id_scheme": "<relative image path>",
                 "counts": {**counts, "total": len(samples)}, "ids_included": False}
    (root / "splits" / "split_v1.json").write_text(json.dumps(split_doc, indent=2))

    labeled = bool(label_counts)
    manifest = {
        "manifest_version": "atom-dataset-v1",
        "dataset": {"name": name, "modality": "image",
                    "dataset_type": "supervised" if labeled else "unlabeled"},
        "counts": {"files": len(files), "samples": split_doc["counts"]},
        "schema": {"mode": "files", "id_column": "id", "columns": []},
        "roles": {"id": "id", "target": ["label"] if labeled else [],
                  "ignore": [], "group": None, "time": None},
        "labels": ([{"column": "label", "classes": dict(sorted(label_counts.items()))}]
                   if labeled else []),
        "split": {"method": "hash", "seed": SPLIT_SEED, "ratios": SPLIT_RATIOS,
                  "file": "splits/split_v1.json"},
        "files": files,
        "checksums": checksums,
    }
    (root / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True))
    (root / "README.md").write_text(
        f"# {name} — ATOM Dataset Package (image)\n\nGenerated by `atom pack-images`; "
        f"{len(samples)} images, {len(label_counts)} classes.\n")
    return root
